version: '3.4'

networks:
  hraftd:
    driver: overlay

services:
  hraftd0:
    networks:
      - hraftd
    image: hraftd
    command: -id node0 -haddr hraftd0:11000 -raddr hraftd0:12000 ~/node0
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s

  hraftd1:
    networks:
      - hraftd
    image: hraftd
    command: -id node1 -join hraftd0:11000 -haddr hraftd1:11000 -raddr hraftd1:12000 ~/node1
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 2
      restart_policy:
        condition: any
        delay: 10s
  
  hraftd2:
    networks:
      - hraftd
    image: hraftd
    command: -id node2 -join hraftd1:11000 -haddr hraftd2:11000 -raddr hraftd2:12000 ~/node2
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s

  # lookup:
  #   networks:
  #     - hraftd
  #   image: alpine
  #   command: nslookup hraftd; sleep 5
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  # hosts:
  #   networks:
  #     - hraftd
  #   image: alpine
  #   command: cat /etc/hosts; sleep 5
  #   deploy:
  #     mode: replicated
  #     replicas: 1